const WS_URL = 'ws://100.111.79.85:1880/ws/dronemaze'//'ws://localhost:3000';

const SHOW_VENTS = false; // Set to false to treat vents as walls
const SHOW_GOAL = false;  // Set to false to treat the goal as empty space
const SHOW_DOORS = false; // Set to false to render doors as walls

const WALL = '#';
const EMPTY = '.';
const START = 'S';
const DOOR = 'D';
const VENT = 'V'; // Re-introducing VENTS
const GOAL = 'G';

// Expanded grid: 26 rows (11+15), 23 columns (15+8)
// Conceptual Room Codes:
// R01: Start Room
// R02, R03, R04, R05, R06, R07, R08: Various interconnected rooms
// H01, H02, H03, H04, H05: Hallways
// G01: Goal Room
const initialGrid = [
    //  0    1     2     3     4     5     6     7     8     9    10    11    12    13    14
    [WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL], // 0
    [WALL, EMPTY, WALL, EMPTY, EMPTY, VENT, EMPTY, EMPTY, WALL, EMPTY, WALL, EMPTY, EMPTY, EMPTY, WALL], // 1
    [WALL, EMPTY, VENT, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL, EMPTY, WALL, EMPTY, EMPTY, EMPTY, WALL], // 2
    [WALL, EMPTY, WALL, WALL, WALL, WALL, EMPTY, EMPTY, WALL, EMPTY, WALL, WALL, EMPTY, WALL, WALL], // 3
    [WALL, EMPTY, EMPTY, VENT, VENT, WALL, WALL, VENT, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL], // 4
    [WALL, WALL, WALL, WALL, VENT, WALL, EMPTY, EMPTY, WALL, WALL, EMPTY, WALL, VENT, EMPTY, WALL], // 5
    [WALL, EMPTY, EMPTY, EMPTY, EMPTY, WALL, WALL, EMPTY, EMPTY, WALL, VENT, WALL, VENT, EMPTY, WALL], // 6
    [WALL, EMPTY, EMPTY, EMPTY, EMPTY, WALL, VENT, WALL, EMPTY, EMPTY, EMPTY, WALL, WALL, EMPTY, WALL], // 7
    [WALL, VENT, WALL, WALL, WALL, WALL, EMPTY, WALL, WALL, VENT, WALL, WALL, VENT, WALL, WALL], // 8
    [WALL, EMPTY, EMPTY, VENT, EMPTY, EMPTY, EMPTY, EMPTY, WALL, WALL, EMPTY, EMPTY, EMPTY, EMPTY, WALL], // 9
    [WALL, EMPTY, EMPTY, WALL, WALL, WALL, WALL, EMPTY, WALL, EMPTY, EMPTY, WALL, VENT, WALL, WALL], // 10
    [WALL, EMPTY, EMPTY, WALL, EMPTY, EMPTY, VENT, EMPTY, WALL, EMPTY, WALL, WALL, EMPTY, EMPTY, WALL], // 11
    [WALL, WALL, WALL, WALL, WALL, EMPTY, WALL, EMPTY, VENT, EMPTY, WALL, EMPTY, EMPTY, EMPTY, WALL], // 12
    [WALL, GOAL, EMPTY, EMPTY, VENT, EMPTY, WALL, EMPTY, WALL, EMPTY, WALL, EMPTY, EMPTY, EMPTY, WALL], // 13
    [WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL], // 14
]

export { initialGrid, START, DOOR, VENT, GOAL, WALL, EMPTY, SHOW_DOORS, SHOW_VENTS, SHOW_GOAL, WS_URL };